# Generated by Django 4.1.5 on 2023-01-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responses',
            new_name='Answers',
        ),
    ]
