# Generated by Django 4.1.5 on 2023-01-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_responses_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
