# Generated by Django 4.1.5 on 2023-01-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans4',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
