# Generated by Django 4.1.5 on 2023-03-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
